import {
  Axe,
  Backpack,
  Beer,
  Binoculars,
  Coffee,
  Cookie,
  Crosshair,
  CupSoda,
  Droplets,
  FileText,
  Fuel,
  Gem,
  Hammer,
  HardHat,
  KeyRound,
  Leaf,
  Newspaper,
  Pill,
  Plus,
  Sandwich,
  Shirt,
  Shovel,
  Utensils,
  Wrench,
} from "lucide-react";
import type { ShopItem } from "./commerce";

export const ITEM_ICONS: Record<ShopItem["icon"], typeof Utensils> = {
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  cookie: Cookie,
  droplets: Droplets,
  fuel: Fuel,
  cup: CupSoda,
  sandwich: Sandwich,
  newspaper: Newspaper,
  shirt: Shirt,
  binoculars: Binoculars,
  plus: Plus,
  leaf: Leaf,
  wrench: Wrench,
  key: KeyRound,
  crosshair: Crosshair,
  hammer: Hammer,
  shovel: Shovel,
  axe: Axe,
  hardhat: HardHat,
  vest: Shirt,
  backpack: Backpack,
  gem: Gem,
  pill: Pill,
  file: FileText,
};
